title: 직관적 개발자
description: 직관적 개발자는 컴퓨터 과학과 프로그래밍의 기본 원리부터 고급 개념까지, 개발자가 직관적으로 이해하고 성장할 수 있는 지식을 공유하는 블로그입니다. 개인적인 학습 여정과 실전 경험을 바탕으로, 복잡한 이론을 쉽게 풀어내어 개발자들이 보다 효율적이고 창의적인 문제 해결 능력을 키울 수 있도록 돕습니다.

url: https://physicallaw.github.io

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

mermaid:
  version: "9.1.6"

heading_anchors: true

nav_enabled: true
nav_sort: case_sensitive
nav_external_links:
  - title: GitHub
    url: https://github.com/physicallaw

footer_content: 'Copyright &copy; 2024 직관적 개발자.'

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
